### ISSUE TITLE
[Feat] HatDetail CollectionView 2번째 Cell(Sticky Header 포함) 구현

### ISSUE THREAD

**Issue by mcrkgus** [DO-SOPT-CDS-APP-2/CDS-APP-2-iOS#20]
## 🛠 Issue

- 2번째 cell 구현
- Sticky Header 붙이기

## 📝 To-do

- [ ] 2번째 cell UI 구현
- [ ] Sticky Header UI 구현
- [ ] Sticky Header 연결
