### ISSUE TITLE
[Feat] HatDetail RecommendInfoCollectionView Cell 구현

### ISSUE THREAD

**Issue by mcrkgus** [DO-SOPT-CDS-APP-2/CDS-APP-2-iOS#33]
## 🛠 Issue

- HatDetail RcommendInfoCollectionView Cell 구현

## 📝 To-do

- [x] Cell 구현
- [x] Sticky Header 구현
- [x] Product Recommend CollectionView 구현
- [x] Event Recommend CollectionView 구현
