### ISSUE TITLE
[Style] HatCategory 조그마한 레이아웃 수정 및 잔잔바리 수정

### ISSUE THREAD

**Issue by chetseoo** [DO-SOPT-CDS-APP-2/CDS-APP-2-iOS#67]
## 🛠 Issue

HatCategory 조그마한 레이아웃 수정 및 잔잔바리 수정
마음에 걸렸던 레이아웃 부분들 수정할겁니다 ..

## 📝 To-do
- [ ] detailProduct 컬뷰에서 상품 이름 line spacing 부여
- [X] realtimeBest 컬뷰에서 할인율 없을 때 가격 레이아웃 수정
- [X] detailProduct 에서 상품 하나 눌렀을때에만 뷰 전환되도록. (지금은 모든 상품 다 누르면 HatDetail뷰컨으로 넘어가는 상태)
- [X] detailProduct 각 상품별 하트수와 평점 수 다르게 데이터화 해놓기
- [X] StringLiterals 로 빼놓을 놈들 빼놓기
